#!/usr/bin/env bash

export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/git/bin
export PATH=$PATH:/usr/X11/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/opt/local/sbin
export PATH=$PATH:/opt/local/bin
export PATH=~/bin:$PATH

# Ruby stuff
export GEM_HOME=~/.gems
export PATH=$PATH:$GEM_HOME/bin

# pyenv stuf
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
