#!/usr/bin/env bash

export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/git/bin
export PATH=$PATH:/usr/X11/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/opt/local/sbin
export PATH=$PATH:/opt/local/bin

# Ruby stuff
export GEM_HOME=~/.gems
export PATH=$PATH:$GEM_HOME/bin
