#!/usr/bin/env bash

export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/git/bin
export PATH=$PATH:/usr/X11/bin
export PATH=$PATH:/opt/local/sbin
