#!/usr/bin/env bash 
# Work related
export NIMBULA_API="https://api.usdev290.nimbula"
export NIMBULA_USER="root/root"
alias na=nimbula-api


#
# Delete all orchestrations
#
deleteorchestrations () {
  for orchestration in `na -uroot/root list orchestration /root/root -Fname `; do echo "Deleting $orchestration"; na -uroot/root delete orchestration $orchestration; done
}


#
# Show NIMBULA env properties
#
naconf () {
    echo "NIMBULA_API: $NIMBULA_API";
   echo "NIMBULA_USER: $NIMBULA_USER";
}


#
# Set NIMBULA env properties
#
naset () {
    echo -n "Setting NIMBULA_API. [Enter for '$NIMBULA_API'] https://";
    read API;
    if [[ -z "${API}" ]]; then
        echo "-> Unchanged"
    else
        export NIMBULA_API=https://$API;
        echo "-> Set"
    fi
    echo -n "Setting NIMBULA_USER. [Enter for '$NIMBULA_USER'] ";
    read USER;
    if [[ -z "${USER}" ]]; then
        echo "-> Unchanged"
    else
        export NIMBULA_USER=$USER;
        echo "-> Set"
    fi
    na authenticate $NIMBULA_USER;
    clear;
}


#
# Use: gitcontribution "Christian Verkerk" "2 weeks ago"
#
gitcontribution () {
    author="$1";
    timeago="$2";
    echo -n "\e[01;32m$author\e[00m:\n";
    git log --shortstat --author $author --since $timeago | grep "files changed" | awk '{files+=$1; inserted+=$4; deleted+=$6} END {print "files changed", files, "lines inserted:", inserted, "lines deleted:", deleted}'
}


#
# Use: gitcontributed "2 weeks ago"
#
gitcontributed () {
    echo "Getting contributions from: $1";
    for author in 'Ruben Stolk' 'Christian Verkerk' 'Pratik Vyas' 'Madhusudan Srinivasa' 'Samyak Bhuta' 'Bill Pieterouiski'; do gitcontribution $author $1; done;
}


#
# Proxy stuff
#
im_at_work () {
    export ALL_PROXY=http://www-proxy.us.oracle.com:80/
    export http_proxy=$ALL_PROXY
    export https_proxy=$ALL_PROXY
    export HTTPS_PROXY=$ALL_PROXY
    sudo sed -i '/oracle/s/^#\ //' /etc/apt/apt.conf.d/00proxy
}

im_at_home () {
    export ALL_PROXY=''
    export HTTPS_PROXY=''
    export http_proxy=''
    export https_proxy=''
    sudo sed -i '/^#/!s/^/#\ /' /etc/apt/apt.conf.d/00proxy
}

