#!/usr/bin/env bash

# Work related
export NIMBULA_API="https://api.usdev290.nimbula"
export NIMBULA_USER="root/root"

alias na=nimbula-api

complete -W 'update,get,list' nimbula-api

naconf () {
    echo "NIMBULA_API: $NIMBULA_API";
    echo "NIMBULA_USER: $NIMBULA_USER";
}

deleteorchestrations () {
  for orchestration in `na -uroot/root list orchestration /root/root -Fname `; do echo "Deleting $orchestration"; na -uroot/root delete orchestration $orchestration; done
}

naset () {
    echo -n "Setting NIMBULA_API. [Enter for '$NIMBULA_API'] https://";
    read API;
    if [[ -z "${API}" ]]; then
        echo "-> Unchanged"
    else
        export NIMBULA_API=https://$API;
        echo "-> Set"
    fi
    echo -n "Setting NIMBULA_USER. [Enter for '$NIMBULA_USER'] ";
    read USER;
    if [[ -z "${USER}" ]]; then
        echo "-> Unchanged"
    else
        export NIMBULA_USER=$USER;
        echo "-> Set"
    fi
    na authenticate $NIMBULA_USER;
    clear;
}
